In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.colheader_justify', 'center')
pd.set_option('display.precision', 3)
def print_results(file):
    df = pd.read_table(file, sep = ';')
    df["average time spent (second)"] = df["average time spent "] / 1000
    print(df.loc[0, "modelName"][-1])
    if df.loc[0, "modelName"][-1] == '-':
        for i in range(len(df)):
            if df.loc[i, 'modelName'][0] == 'o':
                df.loc[i, 'modelName'] += '6-'
            else:
                df.loc[i, 'modelName'] += '4-'
            df.loc[i, 'modelName'] += "crashCost-5" 
    selected_columns = ["modelName", "shieldLevel", 'average undiscounted reward', 'average discounted reward',
           'average time spent (second)']

    selected = df[df.loc[:, "numEpisode"] == df.loc[0, "numEpisodes"]]
    selected = selected.loc[:, selected_columns]
    return selected

In [2]:
import os
files = os.listdir()
files = [file for file in files if "txt" in file]
files.sort()
files

['obstacle-6-crashCost-10-1655878220678.txt',
 'obstacle-6-crashCost-5-1655867304477.txt',
 'refuel-6-8-crashCost-10-1655870627648.txt',
 'refuel-6-8-crashCost-5-1655868393196.txt',
 'rocks-4-crashCost-10-1655874528079.txt',
 'rocks-4-crashCost-5-1655867486267.txt']

In [3]:
i = 0
pd.read_table(files[i], sep = ';')

          modelName          nStates  shieldLevel  numEpisode  numEpisodes  undiscounted reward  discounted reward  timeSpent  average undiscounted reward  average discounted reward  average time spent   isSafeTrace
0   obstacle-6-crashCost-10    37          0            1          10             -16.0              -13.607           1260             -16.000                     -13.607                    1260             0.0
1   obstacle-6-crashCost-10    37          0            2          10              -7.0               -5.732            610             -11.500                      -9.669                     935             1.0
2   obstacle-6-crashCost-10    37          0            3          10             -28.0              -14.481           7137             -17.000                     -11.273                    3002             1.0
3   obstacle-6-crashCost-10    37          0            4          10             -61.0              -18.168          17467             -28.000                     -12.997                    6618             1.0
4   obstacle-6-crashCost-10    37          0            5          10             -24.0              -17.472           2070             -27.200                     -13.892                    5708             0.0
5   obstacle-6-crashCost-10    37          0            6          10             -28.0              -15.425           2598             -27.333                     -14.148                    5190             0.0
6   obstacle-6-crashCost-10    37          0            7          10             -13.0              -11.735            533             -25.286                     -13.803                    4525             0.0
7   obstacle-6-crashCost-10    37          0            8          10             -45.0              -24.418           8492             -27.750                     -15.130                    5020             0.0
8   obstacle-6-crashCost-10    37          0            9          10             -90.0              -27.711          22924             -34.667                     -16.528                    7010             0.0
9   obstacle-6-crashCost-10    37          0           10          10             -29.0              -19.962           1587             -34.100                     -16.871                    6467             0.0
10  obstacle-6-crashCost-10    37          1            1          10             -26.0              -13.993           6005             -26.000                     -13.993                    6005             1.0
11  obstacle-6-crashCost-10    37          1            2          10             -12.0               -8.733           2272             -19.000                     -11.363                    4138             1.0
12  obstacle-6-crashCost-10    37          1            3          10             -13.0               -9.247           2217             -17.000                     -10.658                    3498             1.0
13  obstacle-6-crashCost-10    37          1            4          10              -8.0               -6.395           1293             -14.750                      -9.592                    2946             1.0
14  obstacle-6-crashCost-10    37          1            5          10             -28.0              -14.481           5252             -17.400                     -10.570                    3407             1.0
15  obstacle-6-crashCost-10    37          1            6          10             -32.0              -15.319           9892             -19.833                     -11.361                    4488             1.0
16  obstacle-6-crashCost-10    37          1            7          10             -62.0              -18.210          14731             -25.857                     -12.340                    5951             1.0
17  obstacle-6-crashCost-10    37          1            8          10             -23.0              -13.160           3753             -25.500                     -12.442                    5676             1.0
18  obstacle-6-crashCost-10    37          1            9          10             -42.0              -16.796           6305             -27.333                     -12.926                    5746             1.0
19  obstacle-6-crashCost-10    37          1           10          10             -25.0              -13.730           6467             -27.100                     -13.006                    5818             1.0
20  obstacle-6-crashCost-10    37          2            1          10             -22.0              -12.853           5910             -22.000                     -12.853                    5910             1.0
21  obstacle-6-crashCost-10    37          2            2          10             -47.0              -17.295          10737             -34.500                     -15.074                    8323             1.0
22  obstacle-6-crashCost-10    37          2            3          10             -26.0              -13.993           8150             -31.667                     -14.714                    8265             1.0
23  obstacle-6-crashCost-10    37          2            4          10             -13.0               -9.247           1858             -27.000                     -13.347                    6663             1.0
24  obstacle-6-crashCost-10    37          2            5          10             -60.0              -18.125          16543             -33.600                     -14.302                    8639             1.0
25  obstacle-6-crashCost-10    37          2            6          10             -38.0              -16.294           7895             -34.333                     -14.634                    8515             1.0
26  obstacle-6-crashCost-10    37          2            7          10             -24.0              -13.452           5694             -32.857                     -14.466                    8112             1.0
27  obstacle-6-crashCost-10    37          2            8          10             -42.0              -16.796          11081             -34.000                     -14.757                    8483             1.0
28  obstacle-6-crashCost-10    37          2            9          10             -36.0              -16.002           7510             -34.222                     -14.895                    8375             1.0
29  obstacle-6-crashCost-10    37          2           10          10             -47.0              -17.295          10489             -35.500                     -15.135                    8586             1.0
30  obstacle-6-crashCost-10    37          3            1          10             -99.0              -18.882         251041             -99.000                     -18.882                  251041             1.0
31  obstacle-6-crashCost-10    37          3            2          10             -19.0              -11.830          44567             -59.000                     -15.356                  147804             1.0
32  obstacle-6-crashCost-10    37          3            3          10             -19.0              -11.830          35253             -45.667                     -14.181                  110287             1.0
33  obstacle-6-crashCost-10    37          3            4          10             -67.0              -18.389         166572             -51.000                     -15.233                  124358             1.0
34  obstacle-6-crashCost-10    37          3            5          10             -59.0              -18.079         125134             -52.600                     -15.802                  124513             1.0
35  obstacle-6-crashCost-10    37          3            6          10             -12.0               -8.733          20145             -45.833                     -14.624                  107118             1.0
36  obstacle-6-crashCost-10    37          3            7          10             -35.0              -15.844         102828             -44.286                     -14.798                  106505             1.0
37  obstacle-6-crashCost-10    37          3            8          10             -38.0              -16.294          84785             -43.500                     -14.985                  103790             1.0
38  obstacle-6-crashCost-10    37          3            9          10             -35.0              -15.844         100993             -42.556                     -15.081                  103479             1.0
39  obstacle-6-crashCost-10    37          3           10          10             -47.0              -17.295         130046             -43.000                     -15.302                  106136             1.0
40  obstacle-6-crashCost-10    37          4            1          10             -20.0              -12.189           6291             -20.000                     -12.189                    6291             1.0
41  obstacle-6-crashCost-10    37          4            2          10             -27.0              -14.243          13827             -23.500                     -13.216                   10059             1.0
42  obstacle-6-crashCost-10    37          4            3          10             -20.0              -12.189          10770             -22.333                     -12.874                   10296             1.0
43  obstacle-6-crashCost-10    37          4            4          10             -19.0              -11.830           6328             -21.500                     -12.613                    9304             1.0
44  obstacle-6-crashCost-10    37          4            5          10             -21.0              -12.529           8725             -21.400                     -12.596                    9188             1.0
45  obstacle-6-crashCost-10    37          4            6          10             -21.0              -12.529          10556             -21.333                     -12.585                    9416             1.0
46  obstacle-6-crashCost-10    37          4            7          10             -32.0              -15.319          14381             -22.857                     -12.976                   10125             1.0
47  obstacle-6-crashCost-10    37          4            8          10             -10.0               -7.624           4303             -21.250                     -12.307                    9397             1.0
48  obstacle-6-crashCost-10    37          4            9          10             -10.0               -7.624           3705             -20.000                     -11.786                    8765             1.0
49  obstacle-6-crashCost-10    37          4           10          10             -29.0              -14.707          15180             -20.900                     -12.078                    9406             1.0

In [4]:
print_results(files[i])

0

          modelName          shieldLevel  average undiscounted reward  average discounted reward  average time spent (second)
9   obstacle-6-crashCost-10       0                 -34.1                      -16.871                        6.467
19  obstacle-6-crashCost-10       1                 -27.1                      -13.006                        5.818
29  obstacle-6-crashCost-10       2                 -35.5                      -15.135                        8.586
39  obstacle-6-crashCost-10       3                 -43.0                      -15.302                      106.136
49  obstacle-6-crashCost-10       4                 -20.9                      -12.078                        9.406

In [5]:
i += 1
print_results(files[i])

-

          modelName         shieldLevel  average undiscounted reward  average discounted reward  average time spent (second)
9   obstacle-6-crashCost-5       0                 -12.4                       -9.723                       0.712
19  obstacle-6-crashCost-5       1                 -13.3                       -9.339                       1.734
29  obstacle-6-crashCost-5       2                 -12.7                       -8.911                       1.675
39  obstacle-6-crashCost-5       3                  -9.6                       -7.357                       8.761
49  obstacle-6-crashCost-5       4                 -12.7                       -8.908                       3.991

In [6]:
i += 1
print_results(files[i])

0

          modelName          shieldLevel  average undiscounted reward  average discounted reward  average time spent (second)
9   refuel-6-8-crashCost-10       0                   -5.9                      -4.956                        0.440
19  refuel-6-8-crashCost-10       1                  -90.9                     -22.777                        6.026
29  refuel-6-8-crashCost-10       2                 -150.2                     -22.517                       11.612
39  refuel-6-8-crashCost-10       3                 -105.7                     -22.598                      204.655
49  refuel-6-8-crashCost-10       4                 -142.2                     -24.402                      167.158

In [7]:
i += 1
print_results(files[i])

5

          modelName         shieldLevel  average undiscounted reward  average discounted reward  average time spent (second)
9   refuel-6-8-crashCost-5       0                  -5.8                       -4.879                        0.437
19  refuel-6-8-crashCost-5       1                 -54.0                      -17.239                        3.610
29  refuel-6-8-crashCost-5       2                 -60.6                      -19.560                        4.660
39  refuel-6-8-crashCost-5       3                 -77.1                      -21.471                      141.721
49  refuel-6-8-crashCost-5       4                 -61.5                      -20.906                       69.652

In [8]:
i += 1
print_results(files[i])

0

         modelName        shieldLevel  average undiscounted reward  average discounted reward  average time spent (second)
9   rocks-4-crashCost-10       0                 -25.8                      -16.945                        5.970
19  rocks-4-crashCost-10       1                 -48.0                      -16.985                       39.346
29  rocks-4-crashCost-10       2                 -60.8                      -15.493                       67.546
39  rocks-4-crashCost-10       3                 -35.8                      -14.529                      125.714
49  rocks-4-crashCost-10       4                 -52.0                      -16.432                      130.560

In [9]:
i += 1
print_results(files[i])

-

        modelName        shieldLevel  average undiscounted reward  average discounted reward  average time spent (second)
9   rocks-4-crashCost-5       0                 -13.0                       -9.843                       5.845
19  rocks-4-crashCost-5       1                 -22.4                      -11.202                      12.216
29  rocks-4-crashCost-5       2                 -23.1                      -12.431                       6.939
39  rocks-4-crashCost-5       3                 -13.4                       -9.196                      27.058
49  rocks-4-crashCost-5       4                 -20.4                      -12.439                      24.377

In [ ]:
Remember to update as soon as possible
1. talk about running example of abstraction
    - with prism files
    - explain prism file, observation; transition
    - explain concerns
        - belief support will cross shileds
2. confirm way to get next states
3. ask ways to get the args